### ISSUE TITLE
Does nothing after running main.py

### ISSUE THREAD

**Issue by ChinmayAgarwal3** [sralli/WB-WB-Whatsapp-Birthday-Wishing-Bot#1]
Running this program on Ubuntu 20 , All requirements have been added and tested,  the script is not even throwing an error, and I have been unable to identify what is going wrong...

**Comment by sralli** [comment]
Do provide more details on the issue, but some common troubleshooting tips:
- Ensure that there is a birthday on the current day that you are testing. The program works on the idea that if there is no birthday on that day, do nothing. If there is, run the code to send the message. 

Thanks!
